version: '3'

services:
  nginx:
    container_name: revive_nginx
    image: nginx:1.13-alpine-perl
    volumes:
      - .:/var/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/revive.conf
    ports:
      - 80:80
  php:
    container_name: revive_php
    build:
      context: .
      dockerfile: Dockerfile
    image: revive/php
    volumes:
      - .:/var/app
  mysql:
    container_name: revive_mysql
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
